#!/bin/bash

# Get the list of workspaces
WORKSPACES=$(hyprctl workspaces | grep "Workspace" | cut -d' ' -f2)

# Loop through all workspaces
for WORKSPACE in $WORKSPACES; do
    # Count the number of windows (clients) on the workspace
    WINDOWS_ON_WORKSPACE=$(hyprctl clients | grep "workspace: $WORKSPACE" | wc -l)

    # If there are open windows, add a dot next to the workspace number
    if [ "$WINDOWS_ON_WORKSPACE" -gt 0 ]; then
        echo "$WORKSPACE ●"  # Workspace with open windows (dot)
    else
        echo "$WORKSPACE"     # Empty workspace (no dot)
    fi
done

